package CalculatorApp;


/**
* CalculatorApp/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Thursday, 8 May, 2025 9:47:08 AM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
