package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Thursday, 8 May, 2025 9:47:08 AM IST
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float subtract (float a, float b);
  float multiply (float a, float b);
  float divide (float a, float b);
} // interface CalculatorOperations
